In [3]:
import pandas as pd
import numpy as np
from fsfc.generic import NormalizedCut
from sklearn.pipeline import Pipeline
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
import os
my_path = os.path.abspath('')
my_path = my_path.split('\\')
my_path_py = "\\".join(my_path[:-1])

features = pd.read_csv(my_path_py+'\\2_FeatureBased\\FB2_2009al2013.csv', sep=',')
features = features.iloc[:, 1:]
listadistrito = features.Distrito.values
features = features.drop('Distrito', axis=1)

data = np.array(features)

for i in list(range(3,19)):
    pipeline = Pipeline([
        ('select', NormalizedCut(i)),
        ('cluster', KMeans())
    ])
    print("I es ", i)
    print(np.unique(pipeline.fit_predict(data)))



I es  3
[0 1 2 3 4 5 6 7]
I es  4
[0 1 2 3 4 5 6 7]
I es  5
[0 1 2 3 4 5 6 7]
I es  6
[0 1 2 3 4 5 6 7]
I es  7
[0 1 2 3 4 5 6 7]
I es  8
[0 1 2 3 4 5 6 7]
I es  9
[0 1 2 3 4 5 6 7]
I es  10
[0 1 2 3 4 5 6 7]
I es  11
[0 1 2 3 4 5 6 7]
I es  12
[0 1 2 3 4 5 6 7]
I es  13
[0 1 2 3 4 5 6 7]
I es  14
[0 1 2 3 4 5 6 7]
I es  15
[0 1 2 3 4 5 6 7]
I es  16
[0 1 2 3 4 5 6 7]
I es  17
[0 1 2 3 4 5 6 7]
I es  18
[0 1 2 3 4 5 6 7]


In [4]:
for i in list(range(3,15)):
    pipeline = Pipeline([
        ('select', NormalizedCut(i)),
        ('cluster', AgglomerativeClustering())
    ])
    print("I = ", i)
    print(np.unique(pipeline.fit_predict(data)))



I =  3
[0 1]
I =  4
[0 1]
I =  5
[0 1]
I =  6
[0 1]
I =  7
[0 1]
I =  8
[0 1]
I =  9
[0 1]
I =  10
[0 1]
I =  11
[0 1]
I =  12
[0 1]
I =  13
[0 1]
I =  14
[0 1]


In [5]:
for i in list(range(3,19)):
    pipeline = Pipeline([('select', NormalizedCut(i)),
    ('cluster', DBSCAN())])
    print("I = ", i)
    print(np.unique(pipeline.fit_predict(data)))


I =  3
[0]
I =  4
[-1  0]
I =  5
[-1  0]
I =  6
[-1  0]
I =  7
[-1  0]
I =  8
[-1  0]
I =  9
[-1  0]
I =  10
[-1  0  1  2  3  4  5  6  7  8  9 10]
I =  11
[-1  0  1  2  3  4  5  6  7  8  9 10]
I =  12
[-1  0  1  2  3  4  5  6  7  8  9 10]
I =  13
[-1  0  1  2]
I =  14
[-1  0  1  2]
I =  15
[-1  0  1  2]
I =  16
[-1  0  1  2]
I =  17
[-1]
I =  18
[-1]


In [ ]:
from fsfc.base import BaseFeatureSelector, ClusteringFeatureSelector
b = BaseFeatureSelector
b.fit(features)

In [ ]:
transform(X)